services:
  postgres:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
    restart: always

  rabbitmq:
    image: rabbitmq:4.0.5-management
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:


networks:
  internal:
    driver: bridge
