services:
  postgres:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:4.0.5-management
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  internal:
    driver: bridge